[tool.poetry]
name = "cardroom"
version = "0.1.0"
description = ""
authors = ["Nicola Pesaresi"]
readme = "README.md"
packages = [{ include = "cardroom" }]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.3.1"
pygame = "^2.6.1"
pyyaml = "^6.0.2"
tqdm = "^4.67.1"
ipykernel = "^6.30.1"
matplotlib = "^3.10.6"
pygraphviz = "^1.14"
pytest = "^8.4.2"
pre-commit = "^4.3.0"
pandas = "^2.3.2"
seaborn = "^0.13.2"
scipy = "^1.16.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
