import math
import numpy as np
from typing import Self
from collections import defaultdict
from cardroom.briscola.game.env import BriscolaEnv

def get_legal_actions(observation: dict) -> list:
    """Returns legal actions from an observation.
    Returns:
        list of legal actions."""
    return list(range(0, len(observation["hand"])))

class MCTSNode:
    def __init__(self, observation: dict, env: BriscolaEnv, parent: Self=None, parent_action: int=None):
        """Initializes a node for Monte Carlo Tree Search.
        Args:
            observation: observation of the game state by the current player, as returned by env.
            env: clone of the environment generated from the observation.
            parent: parent node in MCTS tree.
            parent_action: action taken from parent node to reach this node.
        """
        self.observation = observation
        self.env = env
        self.parent = parent
        self.parent_action = parent_action
        self.children = []
        self.visits = 0
        self.wins = 0
        self.draws = 0
        self.losses = 0
        self.untried_actions = get_legal_actions(observation)

    def expand(self) -> Self:
        """Expands a node by taking an action and advancing the environment.
        Returns:
            child: new child node, generated by taking an action.
        """
        child_env = self.env.clone_from_observation()
        action = np.random.choice(self.untried_actions) # currently each child is different, choose depending on parent action
        self.untried_actions.remove(action)
        # play out action and create child node
        child_env.step(int(action))
        child_observation = child_env.get_observation()
        child = MCTSNode(child_observation, child_env, parent=self, parent_action=action)
        self.children.append(child)
        return child

    def is_terminal(self):
        """Checks if the node is terminal (game ends).
        Return"""
        return self.env.done
    
    def rollout(self):
        env = self.env.clone_from_observation()
        current_player_id = env.current_player_id
        while not env.done:
            legal_actions = get_legal_actions(env.get_observation())
            if legal_actions == []:
                print(env.get_observation())
            action = np.random.choice(legal_actions) # RANDOM ACTION: implement a policy for improvement
            env.step(int(action))
        env_result, _ = env.check_result()
        if env_result == 0:
            result = 0
        elif env_result == 1:
            if current_player_id == 0:
                result = 1
            else:
                result = -1
        elif env_result == -1:
            if current_player_id == 1:
                result = 1
            else:
                result = -1
        return result
    
    def backpropagate(self, result):
        self.visits += 1
        if result == 1:
            self.wins += 1
        elif result == 0:
            self.draws += 1
        elif result == -1:
            self.losses += 1
        if self.parent:
            self.parent.backpropagate(result)

    def is_fully_expanded(self):
        return len(self.untried_actions) == 0
    
    def best_child(self, exploration = 0.1):
        weights = [(child.wins - child.losses) / child.visits + exploration * np.sqrt((2 * np.log(self.visits) / child.visits)) for child in self.children]
        return self.children[np.argmax(weights)]
    
    def _tree_policy(self):
        current_node = self
        while not current_node.is_terminal():
            
            if not current_node.is_fully_expanded():
                return current_node.expand()
            else:
                current_node = current_node.best_child()
        return current_node
    
    def best_action(self, simulations):
        for i in range(simulations):
            v = self._tree_policy()
            reward = v.rollout()
            v.backpropagate(reward)
        
        best_child = self.best_child(exploration=0.0)
        return int(best_child.parent_action)
    